superset_dbt_fed:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('WAREHOUSE_HOST') }}"
      port: "{{ env_var('WAREHOUSE_PORT') | int }}"
      dbname: "{{ env_var('WAREHOUSE_DBNAME') }}"
      user: "{{ env_var('WAREHOUSE_USER') }}"
      password: "{{ env_var('WAREHOUSE_PASSWORD') }}"
      schema: staging
