version: 2

sources:
  - name: fred
    schema: raw
    description: "Raw data ingested from the FRED API"

    tables:
      - name: gdpc1
        description: "Quarterly real GDP (GDPC1) as returned by FRED"

        columns:
          - name: date
            description: "Observation date (DATE, parsed from FRED response)"
            tests:
              - not_null

          - name: value
            description: "GDP value (numeric, may contain nulls)"
