version: 2

sources:
  - name: fred
    schema: raw
    tables:
      - name: gdpc1
        description: "Quarterly real GDP from FRED"
        columns:
          - name: date
            tests:
              - not_null
              - unique
          - name: value
            description: "GDP value (numeric, may contain nulls)"
