version: 2
sources:
  - name: fred
    tables:
      - name: gdpc1
        description: "Federal Reserve GDP data for the US"
        columns:
          - name: date
            description: "The date of the GDP data"
          - name: value
            description: "The GDP value"
